# One games list for the whole repository: portal/src/content/games/*.md (title, order, shows,
# notebook, binderUrl) is the source. This script
#   - writes the games table in README.md (between the games-table markers) and the list in Readme.ipynb,
#   - writes the "At a glance" box into the two notebooks without a builder (the builders add it themselves),
#   - and checks that every other place uses the same name: the README section headings
#     ("### <order>. <title>"), each notebook's first heading, and the browser-game strip
#     (portal/src/components/BrowserGames.astro).
#   python3 tools/build_games_list.py   (needs nbformat); exits 1 if a check fails.
# CI runs it with the notebook builders and fails if README.md or Readme.ipynb changed.

import pathlib
import re
import sys

import nbformat

from games import load_games, glance

ROOT = pathlib.Path(__file__).resolve().parent.parent
REPO = 'https://github.com/JanLahmann/Fun-with-Quantum'


games = load_games()
errors = []


def anchor(heading):
    """GitHub's anchor for a heading: lower case, punctuation dropped, spaces to hyphens."""
    return re.sub(r'[^\w\- ]', '', heading.lower()).replace(' ', '-')


# --- README.md: the table, and the section headings ----------------------------------------
rows = ['| Game | What it shows | Launch |', '|---|---|---|']
for g in games:
    heading = f"{g['order']}. {g['title']}"
    nb = g['notebook']
    rows.append(f"| [{heading}](#{anchor(heading)}) | {g['shows']} | [▶ Open]({g['binderUrl']}) · "
                f"[Binder](https://mybinder.org/v2/gh/JanLahmann/Fun-with-Quantum/master?filepath={nb}) · "
                f"[View]({REPO}/blob/master/{nb}) |")
readme = ROOT / 'README.md'
text = readme.read_text()
start, end = '<!-- games-table: generated by tools/build_games_list.py -->', '<!-- /games-table -->'
if start not in text or end not in text:
    sys.exit(f'README.md: markers {start} … {end} missing')
text = text[:text.index(start) + len(start)] + '\n' + '\n'.join(rows) + '\n' + text[text.index(end):]
readme.write_text(text)
headings = re.findall(r'^### (\d+\. .+)$', text, re.M)
for g in games:
    if f"{g['order']}. {g['title']}" not in headings:
        errors.append(f"README.md: no section heading '### {g['order']}. {g['title']}'")

# --- Readme.ipynb: the notebook index ---------------------------------------------------------
index = ROOT / 'Readme.ipynb'
nb = nbformat.read(index, as_version=4)
first = nb.cells[0]
intro = first.source.split('\n1. ')[0].rstrip()
first.source = intro + '\n\n' + '\n'.join(f"{i}. [{g['title']}](./{g['notebook']})" for i, g in enumerate(games, 1))
nbformat.write(nb, index)

# --- the "At a glance" box in the notebooks without a builder ---------------------------------
for name in ['Quantum-Coin-Game.ipynb', 'GHZ-Game.ipynb']:
    nb = nbformat.read(ROOT / name, as_version=4)
    box = next((c for c in nb.cells if c.get('id') == 'at-a-glance'), None)
    if box is None:
        box = nbformat.v4.new_markdown_cell('', id='at-a-glance')
        box.metadata['slideshow'] = {'slide_type': '-'}   # on the title slide
        nb.cells.insert(1, box)
    box.source = glance(name)
    nbformat.write(nb, ROOT / name)

# --- each notebook's first heading ---------------------------------------------------------------
for g in games:
    cell = nbformat.read(ROOT / g['notebook'], as_version=4).cells[0]
    h1 = re.sub(r'<a name="[^"]*"></a>', '', cell.source.splitlines()[0]).strip()
    if h1 != f"# {g['title']}":
        errors.append(f"{g['notebook']}: first heading is '{h1}', expected '# {g['title']}'")

# --- the browser-game strip on the portal ---------------------------------------------------------
strip = (ROOT / 'portal/src/components/BrowserGames.astro').read_text()
titles = {t.replace('’', "'") for t in re.findall(r"title: '([^']+)'", strip)}
for t in titles - {g['title'] for g in games}:
    errors.append(f"BrowserGames.astro: '{t}' is not a game title")

print(f"README.md table and Readme.ipynb: {len(games)} games")
for e in errors:
    print('✗', e)
sys.exit(1 if errors else 0)
